# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_auto_20171221_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(),
        ),
    ]
